# syntax=docker/dockerfile:1
ARG UBUNTU_VERSION=22.04
FROM ubuntu:${UBUNTU_VERSION} AS base

ARG WORKDIR=/workspace

RUN mkdir -p ${WORKDIR}
WORKDIR ${WORKDIR}

# For building kernel
RUN apt-get update && apt-get install -y \
    build-essential libncurses-dev gawk flex bison \
    openssl libssl-dev dkms libelf-dev libudev-dev \
    libpci-dev libiberty-dev autoconf llvm bc bear 

# Other utilities
RUN apt-get install -y cloud-image-utils 
