# syntax=docker/dockerfile:1
FROM baize/simbricks-build AS base

ARG WORKDIR=/workspace

RUN mkdir -p ${WORKDIR}
WORKDIR ${WORKDIR}

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    cloud-image-utils qemu-system-x86 zip libguestfs-tools \
    python3-yaml python3-pip

Run pip3 install easydict