host:
  internet_if: eno1
  qemu_mac_list:
    - 52:54:00:11:11:01
    - 52:54:00:11:11:02
    - 52:54:00:11:11:03
    - 52:54:00:11:11:04
    - 52:54:00:11:11:05
    - 52:54:00:11:11:06
  bridges:
    management:
      name: baize-mana-br
      ip: 10.10.10.2
    provider:
      name: baize-prov-br
      ip: 10.10.11.2
    selfservice:
      name: baize-serv-br
      ip: 10.10.12.2
