openstack:
  id:
    nonadmin:
      project: myproject
      user:
        name: myuser
        pass: mypass
      role: myrole
    admin_pass: &ospass baize
    glance_pass: *ospass
    placement_pass: *ospass
    nova_pass: *ospass
    neutron_pass: *ospass
    rabbit_pass: *ospass
    metadata_secret: *ospass
    keystone_dbpass: *ospass
    glance_dbpass: *ospass
    placement_dbpass: *ospass
    nova_dbpass: *ospass
    neutron_dbpass: *ospass
  network:
    management:
      subnet: 10.10.10.0/24
      mask_len: 24
      gateway: 10.10.10.1
      nameserver: 8.8.8.8
      hosts:
        controller:
          ip: 10.10.10.100
        compute1:
          ip: 10.10.10.101
        compute2:
          ip: 10.10.10.102
    provider:
      subnet: 10.10.11.0/24
      mask_len: 24
      gateway: 10.10.11.1
      nameserver: 8.8.8.8
      ip_pool:
        start: 10.10.11.101
        end: 10.10.11.250
      host_ip_list:
        - &provider_hostip1 10.10.11.111
        - &provider_hostip2 10.10.11.112
        - &provider_hostip3 10.10.11.113
    selfservice:
      subnet: 10.10.12.0/24
      mask_len: 24
      gateway: 10.10.12.1
      nameserver: 8.8.8.8
      host_ip_list:
        - &hostip1 10.10.12.11
        - &hostip2 10.10.12.12 
        - &hostip3 10.10.12.13
        - &hostip4 10.10.12.14
  instances:
    user:
      name: user
      password: pass
    base:
      ubuntu: &ubuntu_base
        iso_url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
        iso_cksum_url: https://cloud-images.ubuntu.com/jammy/current/SHA256SUMS
        disk: 40 # (GB)
    client: &client_instance
      <<: *ubuntu_base
      vcpus: 1
      ram: 1024 # (MB)
      disk: 20 # (GB)
    mysql:
      server:
        <<: *ubuntu_base
        vcpus: 2
        ram: 2048 # (MB)
        ip: *provider_hostip1
      client:
        <<: *client_instance
        ip: *provider_hostip2