openstack:
  virt_type: qemu
  id:
    nonadmin:
      project: myproject
      user:
        name: myuser
        pass: mypass
      role: myrole
    admin_pass: &ospass baize
    glance_pass: *ospass
    placement_pass: *ospass
    nova_pass: *ospass
    neutron_pass: *ospass
    rabbit_pass: *ospass
    metadata_secret: *ospass
    keystone_dbpass: *ospass
    glance_dbpass: *ospass
    placement_dbpass: *ospass
    nova_dbpass: *ospass
    neutron_dbpass: *ospass
  network:
    management:
      subnet: 10.10.10.0
      netmask: 255.255.255.0
      mask_len: 24
      gateway: 10.10.10.1
      nameserver: 8.8.8.8
      hosts:
        controller:
          ip: 10.10.10.100
        compute1:
          ip: 10.10.10.101
        compute2:
          ip: 10.10.10.102
    provider:
      subnet: 10.10.11.0
      netmask: 255.255.255.0
      mask_len: 24
      gateway: 10.10.11.1
      nameserver: 8.8.8.8
      ip_pool:
        start: 10.10.11.101
        end: 10.10.11.250
