platform:
  ubuntu:
    disk:
      iso_url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
      iso_cksum_url: https://cloud-images.ubuntu.com/jammy/current/SHA256SUMS
      size: 250G
    user:
      name: ubuntu
      password: ubuntu
    root:
      password: root
