bridge_script := $(d)bridge.sh
nat_script := $(d)nat.sh

.PHONY: setup-bridges cleanup-bridges setup-nat cleanup-nat
setup-bridges:
	INTERNET_IF=$(INTERNET_IF) BRIDGE_IF=$(SELF_SERVICE_BRIDGE_IF) BRIDGE_IF_CIDR=$(SELF_SERVICE_BRIDGE_IF_IP)/$(SELF_SERVICE_BRIDGE_IF_MASK_LEN) $(bridge_script) setup
	INTERNET_IF=$(INTERNET_IF) BRIDGE_IF=$(MANAGEMENT_BRIDGE_IF) BRIDGE_IF_CIDR=$(MANAGEMENT_BRIDGE_IF_IP)/$(MANAGEMENT_BRIDGE_IF_MASK_LEN) $(bridge_script) setup

cleanup-bridges:
	INTERNET_IF=$(INTERNET_IF) BRIDGE_IF=$(SELF_SERVICE_BRIDGE_IF) BRIDGE_IF_CIDR=$(SELF_SERVICE_BRIDGE_IF_IP)/$(SELF_SERVICE_BRIDGE_IF_MASK_LEN) $(bridge_script) cleanup
	INTERNET_IF=$(INTERNET_IF) BRIDGE_IF=$(MANAGEMENT_BRIDGE_IF) BRIDGE_IF_CIDR=$(MANAGEMENT_BRIDGE_IF_IP)/$(MANAGEMENT_BRIDGE_IF_MASK_LEN) $(bridge_script) setup

setup-nat:
	INTERNET_IF=$(INTERNET_IF) BRIDGE_IF=$(SELF_SERVICE_BRIDGE_IF) $(nat_script) setup
	INTERNET_IF=$(INTERNET_IF) BRIDGE_IF=$(MANAGEMENT_BRIDGE_IF) $(nat_script) setup

cleanup-nat:
	INTERNET_IF=$(INTERNET_IF) BRIDGE_IF=$(SELF_SERVICE_BRIDGE_IF) $(nat_script) cleanup
	INTERNET_IF=$(INTERNET_IF) BRIDGE_IF=$(MANAGEMENT_BRIDGE_IF) $(nat_script) cleanup
