host:
  internet_if: eno1
  qemu_mac_list:
    - 52:54:00:11:11:01
    - 52:54:00:11:11:02
    - 52:54:00:11:11:03
    - 52:54:00:11:11:04
    - 52:54:00:11:11:05
    - 52:54:00:11:11:06
  bridges:
    management:
      name: br-cxlsim-mana
      ip: 10.10.10.1
      netmask_len: 24
    provider:
      name: br-cxlsim-prov
      ip: 10.10.11.1
      netmask_len: 24
    selfservice:
      name: br-cxlsim-serv
      ip: 10.10.12.1
      netmask_len: 24
