platform:
  ubuntu:
    disks:
      base:
        iso_url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
        iso_cksum_url: https://cloud-images.ubuntu.com/noble/current/SHA256SUMS
        size: 40G
      gateway:
        size: 40G
      controller:
        size: 250G
      compute:
        size: 250G 
    user:
      name: cxlsim
      password: cxlsim
    root:
      password: root
