network:
    version: 2
    renderer: networkd
    ethernets:
        enp0s3:
            dhcp4: false
            addresses:
              - 10.10.10.101/24
            nameservers:
              addresses:
                - 8.8.8.8
            routes:
              - to: default
                via: 10.10.10.1